### ISSUE TITLE
Responsive Images 101, Part 7: Type

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#735]
http://blog.cloudfour.com/responsive-images-101-part-7-type/

**Comment by stefanjudis** [comment]
:+1:

**Comment by marcobiedermann** [comment]
@stefanjudis 
Hmm, there are many articles about responsive images in this series:
1. Definitions
1. Img Required
1. Srcset Display Density
1. Srcset Width Descriptors
1. Sizes
1. Picture Element
1. Type
1. CSS Responsive Images
1. Image breakpoints

This article is not bad but than we should add all of them. We already list a lot of resources on this topic.
I prefer [this article](http://www.useragentman.com/blog/2015/01/14/using-webp-jpeg2000-jpegxr-apng-now-with-picturefill-and-modernizr/) because it got a more in depth view of it.

**Comment by stefanjudis** [comment]
Fair enough. :)
