### ISSUE TITLE
speed-up-wordpress

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#853]
http://brianjackson.io/speed-up-wordpress/

**Comment by radibit** [comment]
I'm not convinced about this article, too basic maybe :smiley:  In my relatively little experience with WordPress I can say that all the points without number one ( I really don't have opinion on this ) are some of the `must-do` things to do in order to achieve smooth experience with this technology. Especially the point about the plugins - that was one of the first things I learned.

**Comment by stefanjudis** [comment]
go ahead and close it then. thanks. :)

Radimir Bitsov <notifications@github.com> schrieb am Di., 22. Sep. 2015 um
22:00 Uhr:
