### ISSUE TITLE
Why Performance Matters: The Perception Of Time

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#857]
http://www.smashingmagazine.com/2015/09/why-performance-matters-the-perception-of-time/

**Comment by stefanjudis** [comment]
Not sure about that one.

Can you give me a statement here?

@radibit @marhigh @marcobiedermann

**Comment by radibit** [comment]
Hey @stefanjudis 

I think the article is interesting, because of the alternative perspective on the topic, but it's hard to tell right now whether it should be included or not, because that's only the first part of what seems to be a series of articles :smiley: 

If we are looking only at this specific blog post, I might say :-1: and there two things that are shaping my opinion:

- I think if we abstract the article from the psychological explanation for the perception of the time, you can find that the provided concepts and ideas are really the basic well known optimisations.
- The main focus is slightly different in terms of the resources that have been added previously - it's more oriented on the scientific explanation than providing new knowledge in the web performance area.

**Comment by marcobiedermann** [comment]
I have to agree with @radibit. At the current state I would not include it because it just gives a brief into the topic.
In my opinion I think we should either wait for the upcoming posts or add a level system (e.g. beginner, advanced, expert…) related to #228.

**Comment by stefanjudis** [comment]
Okay - so we're closing this one here... as I don't think we'll tackle the level system soon, right?

Feel free to reopen if you don't agree. :bowtie:
